version: '3.9'

services:

  aws-sam-api-server:
    image: marcellodesales/aws-sam-server:${VERSION:-latest}
    build:
      context: .

    environment:
      SAM_CLI_TELEMETRY: false

    volumes:
      - $PWD:$PWD
      # Needed so a docker container can be run from inside a docker container
      - /var/run/docker.sock:/var/run/docker.sock 
      - ~/.aws/:/root/.aws:ro

    working_dir: $PWD

    # https://github.com/aws/aws-sam-cli/issues/2436#issuecomment-1200922963
    command: sam local start-api -p 3000 --host 0.0.0.0 --docker-network aws_backend --container-host host.docker.internal

    ports:
      - "3000:3000"

    networks:
      - "backend"

networks:
  backend:
    name: aws_backend
    driver: bridge
