version: '3.9'

# Setup a provide network for local deployments of aws services
networks:
  backend:
    name: aws_backend
    driver: bridge

services:

  aws-sam-api-server:
    image: marcellodesales/aws-sam-server:${VERSION:-latest}
    build:
      context: .

    # A container will run in a dir with the same name as current dir
    working_dir: $PWD

    volumes:
      # The volumes for the current dir is mounted
      - $PWD:$PWD

      # Needed so a docker container can be run from inside a docker container
      - /var/run/docker.sock:/var/run/docker.sock 

      # The settings to your aws if needed
      - ~/.aws/:/root/.aws:ro

    networks:
      - "backend"

    ports:
      # SAM API server runs on port 3000
      - "3000:3000"

    environment:
      # Just don't send telemetry data to AWS...
      SAM_CLI_TELEMETRY: false

      # The docker network created
      DOCKER_NETWORK: aws_backend
